/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserRouteElementsImport } from './routes/userRouteElements'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UserRouteElementsRoute = UserRouteElementsImport.update({
  id: '/userRouteElements',
  path: '/userRouteElements',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/userRouteElements': {
      id: '/userRouteElements'
      path: '/userRouteElements'
      fullPath: '/userRouteElements'
      preLoaderRoute: typeof UserRouteElementsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/userRouteElements': typeof UserRouteElementsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/userRouteElements': typeof UserRouteElementsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/userRouteElements': typeof UserRouteElementsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/userRouteElements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/userRouteElements'
  id: '__root__' | '/' | '/userRouteElements'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRouteElementsRoute: typeof UserRouteElementsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRouteElementsRoute: UserRouteElementsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/userRouteElements"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/userRouteElements": {
      "filePath": "userRouteElements.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
